### ISSUE TITLE
Issue on page /docs/econ_intro/intro_to_data/intro_to_data.html

### ISSUE THREAD

**Issue by KhannaSahaj** [ubcecon/comet-project#1]
Intro to Data: Exercise - Adding a variable

Even though I have done the exercise correctly. I still can't get the test to show correct.
![](https://piazza.com/redirect/s3?bucket=uploads&prefix=paste%2Fkt7jsvy3lt944h%2F6fb1f0191e4c713bda58236c471827eb5e8962175291d59e0943a81a30c65274%2FScreen_Shot_2022-09-21_at_8.14.18_PM.png)

**Comment by jlgraves-ubc** [comment]
Hi - thanks for logging this issue.

We are looking into fixing this!  Much appreciated.

**Comment by jlgraves-ubc** [comment]
This will be fixed in the next rolling update.
